doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Skeleton:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/app'
        prefix: 'Skeleton'
        alias: App
